language: node_js
sudo: false
node_js:
- '5'
install:
- npm install
script:
- npm run build
- npm run test
after_script:
- npm run coveralls
deploy:
  provider: npm
  api_key:
    secure: RyC508zFjFoaZ6BQvuxbVGVDw2PTk14LcEtbcITG3VMBHpiElI3GsjeAbsyZZwdyIxma1OkNZ/dctcpQ+B+Xnb3FKN/NyZlLtlNTVTrazaFAJCgZjyabgxavlTYSdin4d4HkOe4HoZi20Cx6tM9cvB0OqeeV+0efIwVxbbaHu+E=
